import type { Metadata } from "next";
import "./styles/globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className=" flex items-center justify-center flex-row">
				{children}
			</body>
		</html>
	);
}
